### ISSUE TITLE
Inclua para favicon

### ISSUE THREAD

**Issue by weiner-rezcue98** [Senac-Rio-Devs/defender#5]
![f279b6702665aec566dce6a5eeae301f](https://github.com/Senac-Rio-Devs/defender/assets/119900774/c8156ed7-b9ed-448a-bb81-facebba60634)

**Comment by Senac-Rio-Devs** [comment]
deixa comigo

**Comment by weiner-rezcue98** [comment]
Prefere que eu faça, tipo é só converter mesmo, só pra dar aquele vislumbre

**Comment by weiner-rezcue98** [comment]
Vai deixando o código limpo do começo ao fim pra ter os logs que foram criados do zero absoluto

**Comment by senac-rj-sesc** [comment]
Tem que privar o repositório está publico pra mim

**Comment by weiner-rezcue98** [comment]
> Tem que privar o repositório está publico pra mim

Sim, vou fazer isso!

**Comment by weiner-rezcue98** [comment]
> deixa comigo

Espero

**Comment by weiner-rezcue98** [comment]
Finalizando
